name = "rhpix"
version = "0.1.0"
license = "license"
author = "Jane Doe"
maintainer = "jane.doe@example.com"
copyright = "2020 Jane Doe"

[ library ]
source-dir="src"

[[ executable ]]
name="mainApp"
source-dir="app"
main="main.f90"

[[ test ]]
name="test1"
source-dir="test"
main="test1.c"
