name = "rhpix"
version = "0.1.0"
license = "license"
author = "Jane Doe"
maintainer = "jane.doe@example.com"
copyright = "2020 Jane Doe"

[ library ]
source-dir="src"

# [[ executable ]]
# name="mainApp"
# source-dir="src"
# main="main.f90"
